#include "nsEngineTypes.h"

#include "Private/API_VK/nsVulkan.cpp"
#include "Private/API_VK/nsVulkanRenderPass.cpp"
#include "Private/API_VK/nsVulkanResource.cpp"
#include "Private/API_VK/nsVulkanShaderPipeline.cpp"
#include "Private/API_VK/nsVulkanShaderResource.cpp"
#include "Private/API_VK/nsVulkanSwapchain.cpp"

/*
#include "Private/nsGeometryFactory.cpp"
#include "Private/nsTexture.cpp"
#include "Private/nsMaterial.cpp"
#include "Private/nsMesh.cpp"
#include "Private/nsFont.cpp"
#include "Private/nsConsole.cpp"
#include "Private/nsAnimation.cpp"
#include "Private/nsGUICore.cpp"
#include "Private/nsGUIFramework.cpp"
#include "Private/nsRenderContextWorld.cpp"
#include "Private/nsRenderer.cpp"
#include "Private/nsShaderManager.cpp"
#include "Private/nsRenderManager.cpp"
#include "Private/nsAssetManager.cpp"
#include "Private/nsAssetImporter.cpp"
#include "Private/nsViewport.cpp"
#include "Private/nsPhysics.cpp"
#include "Private/nsActor.cpp"
#include "Private/nsActorComponents.cpp"
#include "Private/nsLevel.cpp"
#include "Private/nsWorld.cpp"
#include "Private/nsEngine.cpp"
#include "Private/nsGameApplication.cpp"
*/

#include "Private/nsActorComponents.cpp"
#include "Private/nsRenderComponents.cpp"
#include "Private/nsPhysicsComponents.cpp"
#include "Private/nsNavigationComponents.cpp"

#include "Private/nsActor.cpp"
#include "Private/nsActorAsset.cpp"
#include "Private/nsLevel.cpp"
#include "Private/nsWorld.cpp"
